// Code generated by gen.py; DO NOT EDIT
package remark

type Remark struct {
	Type                         Type   `json:"type"`
	Fight                        string `json:"fight,omitempty"`
	ItemWowheadAttr              string `json:"item_wowhead_attr,omitempty"`
	WowheadAttr                  string `json:"wowhead_attr,omitempty"`
	Count                        int    `json:"count,omitempty"`
	Slot                         string `json:"slot,omitempty"`
	EnchantID                    int64  `json:"enchant_id,omitempty"`
	ExpectedPoints               int64  `json:"expected_points,omitempty"`
	PointsUsed                   int64  `json:"points_used,omitempty"`
	SpellID                      int64  `json:"spell_id,omitempty"`
	SuggestedSpellID             int64  `json:"suggested_spell_id,omitempty"`
	SpellWowheadAttr             string `json:"spell_wowhead_attr,omitempty"`
	HigherRankedSpellWowheadAttr string `json:"higher_ranked_spell_wowhead_attr,omitempty"`
	PossibleCasts                int64  `json:"possible_casts,omitempty"`
	ActualCasts                  int64  `json:"actual_casts,omitempty"`
	Threshold                    int64  `json:"threshold,omitempty"`
	ActualPercentageOfUse        int64  `json:"actual_percentage_of_use,omitempty"`

	UUID string `json:"uuid"`
}
