// Code generated by gen.py; DO NOT EDIT
package remark

type InvalidFood struct {
	WowheadAttr string `json:"wowhead_attr"`
}

func (InvalidFood) getType() Type   { return Type_InvalidFood }
func (InvalidFood) is(rt Type) bool { return rt == Type_InvalidFood }
func (md InvalidFood) apply(r *Remark) {
	r.WowheadAttr = md.WowheadAttr
}
