// Code generated by gen.py; DO NOT EDIT
package remark

type InvalidEnchant struct {
	ItemWowheadAttr string `json:"item_wowhead_attr"`
	WowheadAttr     string `json:"wowhead_attr"`
	Slot            string `json:"slot"`
	EnchantID       int64  `json:"enchant_id"`
}

func (InvalidEnchant) getType() Type   { return Type_InvalidEnchant }
func (InvalidEnchant) is(rt Type) bool { return rt == Type_InvalidEnchant }
func (md InvalidEnchant) apply(r *Remark) {
	r.ItemWowheadAttr = md.ItemWowheadAttr
	r.WowheadAttr = md.WowheadAttr
	r.Slot = md.Slot
	r.EnchantID = md.EnchantID
}
