// Code generated by gen.py; DO NOT EDIT
package remark

type Type string

const (
	Type_InvalidGem                    = "invalid_gem"
	Type_MissingGems                   = "missing_gems"
	Type_NoEnchant                     = "no_enchant"
	Type_InvalidEnchant                = "invalid_enchant"
	Type_NoTemporaryEnchant            = "no_temporary_enchant"
	Type_InvalidTemporaryEnchant       = "invalid_temporary_enchant"
	Type_NoTemporaryEnchantButWindfury = "no_temporary_enchant_but_windfury"
	Type_MissingBattleElixir           = "missing_battle_elixir"
	Type_MissingGuardianElixir         = "missing_guardian_elixir"
	Type_MissingFood                   = "missing_food"
	Type_InvalidBattleElixir           = "invalid_battle_elixir"
	Type_InvalidGuardianElixir         = "invalid_guardian_elixir"
	Type_InvalidFood                   = "invalid_food"
	Type_InvalidTalentPoints           = "invalid_talent_points"
	Type_CastHigherRankAvailable       = "cast_higher_rank_available"
	Type_MissingItemInSlot             = "missing_item_in_slot"
	Type_MetaNotActivated              = "meta_not_activated"
)
