// Code generated by gen.py; DO NOT EDIT
package remark

type InvalidBattleElixir struct {
	WowheadAttr string `json:"wowhead_attr"`
}

func (InvalidBattleElixir) getType() Type   { return Type_InvalidBattleElixir }
func (InvalidBattleElixir) is(rt Type) bool { return rt == Type_InvalidBattleElixir }
func (md InvalidBattleElixir) apply(r *Remark) {
	r.WowheadAttr = md.WowheadAttr
}
