// Code generated by gen.py; DO NOT EDIT
package remark

type MetaNotActivated struct {
	ItemWowheadAttr string `json:"item_wowhead_attr"`
	WowheadAttr     string `json:"wowhead_attr"`
}

func (MetaNotActivated) getType() Type   { return Type_MetaNotActivated }
func (MetaNotActivated) is(rt Type) bool { return rt == Type_MetaNotActivated }
func (md MetaNotActivated) apply(r *Remark) {
	r.ItemWowheadAttr = md.ItemWowheadAttr
	r.WowheadAttr = md.WowheadAttr
}
