// Code generated by gen.py; DO NOT EDIT
package remark

type MissingItemInSlot struct {
	Slot string `json:"slot"`
}

func (MissingItemInSlot) getType() Type   { return Type_MissingItemInSlot }
func (MissingItemInSlot) is(rt Type) bool { return rt == Type_MissingItemInSlot }
func (md MissingItemInSlot) apply(r *Remark) {
	r.Slot = md.Slot
}
