// Code generated by gen.py; DO NOT EDIT
package remark

type CastHigherRankAvailable struct {
	SpellID                      int64  `json:"spell_id"`
	SuggestedSpellID             int64  `json:"suggested_spell_id"`
	SpellWowheadAttr             string `json:"spell_wowhead_attr"`
	HigherRankedSpellWowheadAttr string `json:"higher_ranked_spell_wowhead_attr"`
	Count                        int    `json:"count"`
}

func (CastHigherRankAvailable) getType() Type   { return Type_CastHigherRankAvailable }
func (CastHigherRankAvailable) is(rt Type) bool { return rt == Type_CastHigherRankAvailable }
func (md CastHigherRankAvailable) apply(r *Remark) {
	r.SpellID = md.SpellID
	r.SuggestedSpellID = md.SuggestedSpellID
	r.SpellWowheadAttr = md.SpellWowheadAttr
	r.HigherRankedSpellWowheadAttr = md.HigherRankedSpellWowheadAttr
	r.Count = md.Count
}
