// Code generated by gen.py; DO NOT EDIT
package remark_test

import (
	"testing"

	"github.com/origin-finkle/logs/internal/models/remark"
)

func TestInvalidTalentPoints_applyToRemark(t *testing.T) {
	md := remark.InvalidTalentPoints{}
	remark.New(md, "test")
}
