// Code generated by gen.py; DO NOT EDIT
package remark

type InvalidGem struct {
	ItemWowheadAttr string `json:"item_wowhead_attr"`
	WowheadAttr     string `json:"wowhead_attr"`
}

func (InvalidGem) getType() Type   { return Type_InvalidGem }
func (InvalidGem) is(rt Type) bool { return rt == Type_InvalidGem }
func (md InvalidGem) apply(r *Remark) {
	r.ItemWowheadAttr = md.ItemWowheadAttr
	r.WowheadAttr = md.WowheadAttr
}
