// Code generated by gen.py; DO NOT EDIT
package remark

type MissingGuardianElixir struct {
}

func (MissingGuardianElixir) getType() Type   { return Type_MissingGuardianElixir }
func (MissingGuardianElixir) is(rt Type) bool { return rt == Type_MissingGuardianElixir }
func (md MissingGuardianElixir) apply(r *Remark) {
}
