// Code generated by gen.py; DO NOT EDIT
package remark

type CouldMaximizeCasts struct {
	SpellID               int64  `json:"spell_id"`
	PossibleCasts         int64  `json:"possible_casts"`
	ActualCasts           int64  `json:"actual_casts"`
	Threshold             int64  `json:"threshold"`
	ActualPercentageOfUse int64  `json:"actual_percentage_of_use"`
	SpellWowheadAttr      string `json:"spell_wowhead_attr"`
}

func (CouldMaximizeCasts) getType() Type   { return Type_CouldMaximizeCasts }
func (CouldMaximizeCasts) is(rt Type) bool { return rt == Type_CouldMaximizeCasts }
func (md CouldMaximizeCasts) apply(r *Remark) {
	r.SpellID = md.SpellID
	r.PossibleCasts = md.PossibleCasts
	r.ActualCasts = md.ActualCasts
	r.Threshold = md.Threshold
	r.ActualPercentageOfUse = md.ActualPercentageOfUse
	r.SpellWowheadAttr = md.SpellWowheadAttr
}
