// Code generated by gen.py; DO NOT EDIT
package remark

type InvalidTalentPoints struct {
	ExpectedPoints int64 `json:"expected_points"`
	PointsUsed     int64 `json:"points_used"`
}

func (InvalidTalentPoints) getType() Type   { return Type_InvalidTalentPoints }
func (InvalidTalentPoints) is(rt Type) bool { return rt == Type_InvalidTalentPoints }
func (md InvalidTalentPoints) apply(r *Remark) {
	r.ExpectedPoints = md.ExpectedPoints
	r.PointsUsed = md.PointsUsed
}
