// Code generated by gen.py; DO NOT EDIT
package remark

type MissingBattleElixir struct {
}

func (MissingBattleElixir) getType() Type   { return Type_MissingBattleElixir }
func (MissingBattleElixir) is(rt Type) bool { return rt == Type_MissingBattleElixir }
func (md MissingBattleElixir) apply(r *Remark) {
}
