// Code generated by gen.py; DO NOT EDIT
package remark

type MissingGems struct {
	ItemWowheadAttr string `json:"item_wowhead_attr"`
	Count           int    `json:"count"`
}

func (MissingGems) getType() Type   { return Type_MissingGems }
func (MissingGems) is(rt Type) bool { return rt == Type_MissingGems }
func (md MissingGems) apply(r *Remark) {
	r.ItemWowheadAttr = md.ItemWowheadAttr
	r.Count = md.Count
}
