// Code generated by gen.py; DO NOT EDIT
package remark

type InvalidGuardianElixir struct {
	WowheadAttr string `json:"wowhead_attr"`
}

func (InvalidGuardianElixir) getType() Type   { return Type_InvalidGuardianElixir }
func (InvalidGuardianElixir) is(rt Type) bool { return rt == Type_InvalidGuardianElixir }
func (md InvalidGuardianElixir) apply(r *Remark) {
	r.WowheadAttr = md.WowheadAttr
}
