name: golangci-lint
on:
  - push
permissions:
  contents: read
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0
          skip-go-installation: true
      - name: Tests
        run: |
          svn checkout https://github.com/origin-finkle/wcl-origin/trunk/data/config
          CONFIG_FOLDER=`pwd`/config bash test.sh